#!/usr/bin/env bash
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
ENV_FILE="${HERMES_DASHBOARD_ENV_FILE:-$HOME/.config/agentic-os/hermes-dashboard.env}"

if [ -f "$ENV_FILE" ]; then
  set -a
  # Generated by install-hermes-dashboard.sh; owner-readable only.
  . "$ENV_FILE"
  set +a
fi

if ss -ltn 2>/dev/null | grep -q ':9119 '; then
  exit 0
fi

exec "$HOME/.local/bin/hermes" dashboard \
  --host 127.0.0.1 \
  --port 9119 \
  --no-open \
  --skip-build
